package com.song.pojo;

import java.util.Date;

public class BusCustomer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_customer.identity
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    private String identity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_customer.custname
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    private String custname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_customer.sex
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_customer.address
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_customer.phone
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_customer.career
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    private String career;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_customer.createtime
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_customer.identity
     *
     * @return the value of bus_customer.identity
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public String getIdentity() {
        return identity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_customer.identity
     *
     * @param identity the value for bus_customer.identity
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public void setIdentity(String identity) {
        this.identity = identity == null ? null : identity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_customer.custname
     *
     * @return the value of bus_customer.custname
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public String getCustname() {
        return custname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_customer.custname
     *
     * @param custname the value for bus_customer.custname
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public void setCustname(String custname) {
        this.custname = custname == null ? null : custname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_customer.sex
     *
     * @return the value of bus_customer.sex
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_customer.sex
     *
     * @param sex the value for bus_customer.sex
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_customer.address
     *
     * @return the value of bus_customer.address
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_customer.address
     *
     * @param address the value for bus_customer.address
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_customer.phone
     *
     * @return the value of bus_customer.phone
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_customer.phone
     *
     * @param phone the value for bus_customer.phone
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_customer.career
     *
     * @return the value of bus_customer.career
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public String getCareer() {
        return career;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_customer.career
     *
     * @param career the value for bus_customer.career
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public void setCareer(String career) {
        this.career = career == null ? null : career.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_customer.createtime
     *
     * @return the value of bus_customer.createtime
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_customer.createtime
     *
     * @param createtime the value for bus_customer.createtime
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}