package com.song.pojo;

import java.util.Date;

public class BusCheck {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_check.checkid
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    private String checkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_check.checkdate
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    private Date checkdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_check.checkdesc
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    private String checkdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_check.problem
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    private String problem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_check.paymoney
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    private Double paymoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_check.opername
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    private String opername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_check.rentid
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    private String rentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_check.createtime
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_check.checkid
     *
     * @return the value of bus_check.checkid
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public String getCheckid() {
        return checkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_check.checkid
     *
     * @param checkid the value for bus_check.checkid
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public void setCheckid(String checkid) {
        this.checkid = checkid == null ? null : checkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_check.checkdate
     *
     * @return the value of bus_check.checkdate
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public Date getCheckdate() {
        return checkdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_check.checkdate
     *
     * @param checkdate the value for bus_check.checkdate
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public void setCheckdate(Date checkdate) {
        this.checkdate = checkdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_check.checkdesc
     *
     * @return the value of bus_check.checkdesc
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public String getCheckdesc() {
        return checkdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_check.checkdesc
     *
     * @param checkdesc the value for bus_check.checkdesc
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public void setCheckdesc(String checkdesc) {
        this.checkdesc = checkdesc == null ? null : checkdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_check.problem
     *
     * @return the value of bus_check.problem
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public String getProblem() {
        return problem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_check.problem
     *
     * @param problem the value for bus_check.problem
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public void setProblem(String problem) {
        this.problem = problem == null ? null : problem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_check.paymoney
     *
     * @return the value of bus_check.paymoney
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public Double getPaymoney() {
        return paymoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_check.paymoney
     *
     * @param paymoney the value for bus_check.paymoney
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public void setPaymoney(Double paymoney) {
        this.paymoney = paymoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_check.opername
     *
     * @return the value of bus_check.opername
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public String getOpername() {
        return opername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_check.opername
     *
     * @param opername the value for bus_check.opername
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public void setOpername(String opername) {
        this.opername = opername == null ? null : opername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_check.rentid
     *
     * @return the value of bus_check.rentid
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public String getRentid() {
        return rentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_check.rentid
     *
     * @param rentid the value for bus_check.rentid
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public void setRentid(String rentid) {
        this.rentid = rentid == null ? null : rentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_check.createtime
     *
     * @return the value of bus_check.createtime
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_check.createtime
     *
     * @param createtime the value for bus_check.createtime
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}