package com.song.pojo;

import java.util.Date;

public class BusCar {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_car.carnumber
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    private String carnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_car.cartype
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    private String cartype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_car.color
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    private String color;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_car.price
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_car.rentprice
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    private Double rentprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_car.deposit
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    private Double deposit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_car.isrenting
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    private Integer isrenting;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_car.description
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_car.carimg
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    private String carimg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_car.createtime
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_car.carnumber
     *
     * @return the value of bus_car.carnumber
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public String getCarnumber() {
        return carnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_car.carnumber
     *
     * @param carnumber the value for bus_car.carnumber
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public void setCarnumber(String carnumber) {
        this.carnumber = carnumber == null ? null : carnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_car.cartype
     *
     * @return the value of bus_car.cartype
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public String getCartype() {
        return cartype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_car.cartype
     *
     * @param cartype the value for bus_car.cartype
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public void setCartype(String cartype) {
        this.cartype = cartype == null ? null : cartype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_car.color
     *
     * @return the value of bus_car.color
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_car.color
     *
     * @param color the value for bus_car.color
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_car.price
     *
     * @return the value of bus_car.price
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_car.price
     *
     * @param price the value for bus_car.price
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_car.rentprice
     *
     * @return the value of bus_car.rentprice
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public Double getRentprice() {
        return rentprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_car.rentprice
     *
     * @param rentprice the value for bus_car.rentprice
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public void setRentprice(Double rentprice) {
        this.rentprice = rentprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_car.deposit
     *
     * @return the value of bus_car.deposit
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public Double getDeposit() {
        return deposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_car.deposit
     *
     * @param deposit the value for bus_car.deposit
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public void setDeposit(Double deposit) {
        this.deposit = deposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_car.isrenting
     *
     * @return the value of bus_car.isrenting
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public Integer getIsrenting() {
        return isrenting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_car.isrenting
     *
     * @param isrenting the value for bus_car.isrenting
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public void setIsrenting(Integer isrenting) {
        this.isrenting = isrenting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_car.description
     *
     * @return the value of bus_car.description
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_car.description
     *
     * @param description the value for bus_car.description
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_car.carimg
     *
     * @return the value of bus_car.carimg
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public String getCarimg() {
        return carimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_car.carimg
     *
     * @param carimg the value for bus_car.carimg
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public void setCarimg(String carimg) {
        this.carimg = carimg == null ? null : carimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_car.createtime
     *
     * @return the value of bus_car.createtime
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_car.createtime
     *
     * @param createtime the value for bus_car.createtime
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}