package com.song.pojo;

import java.util.Date;

public class BusRent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_rent.rentid
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    private String rentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_rent.price
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_rent.begindate
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    private Date begindate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_rent.returndate
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    private Date returndate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_rent.rentflag
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    private Integer rentflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_rent.identity
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    private String identity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_rent.carnumber
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    private String carnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_rent.opername
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    private String opername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_rent.createtime
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_rent.rentid
     *
     * @return the value of bus_rent.rentid
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public String getRentid() {
        return rentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_rent.rentid
     *
     * @param rentid the value for bus_rent.rentid
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public void setRentid(String rentid) {
        this.rentid = rentid == null ? null : rentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_rent.price
     *
     * @return the value of bus_rent.price
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_rent.price
     *
     * @param price the value for bus_rent.price
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_rent.begindate
     *
     * @return the value of bus_rent.begindate
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public Date getBegindate() {
        return begindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_rent.begindate
     *
     * @param begindate the value for bus_rent.begindate
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public void setBegindate(Date begindate) {
        this.begindate = begindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_rent.returndate
     *
     * @return the value of bus_rent.returndate
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public Date getReturndate() {
        return returndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_rent.returndate
     *
     * @param returndate the value for bus_rent.returndate
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public void setReturndate(Date returndate) {
        this.returndate = returndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_rent.rentflag
     *
     * @return the value of bus_rent.rentflag
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public Integer getRentflag() {
        return rentflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_rent.rentflag
     *
     * @param rentflag the value for bus_rent.rentflag
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public void setRentflag(Integer rentflag) {
        this.rentflag = rentflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_rent.identity
     *
     * @return the value of bus_rent.identity
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public String getIdentity() {
        return identity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_rent.identity
     *
     * @param identity the value for bus_rent.identity
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public void setIdentity(String identity) {
        this.identity = identity == null ? null : identity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_rent.carnumber
     *
     * @return the value of bus_rent.carnumber
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public String getCarnumber() {
        return carnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_rent.carnumber
     *
     * @param carnumber the value for bus_rent.carnumber
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public void setCarnumber(String carnumber) {
        this.carnumber = carnumber == null ? null : carnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_rent.opername
     *
     * @return the value of bus_rent.opername
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public String getOpername() {
        return opername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_rent.opername
     *
     * @param opername the value for bus_rent.opername
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public void setOpername(String opername) {
        this.opername = opername == null ? null : opername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_rent.createtime
     *
     * @return the value of bus_rent.createtime
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_rent.createtime
     *
     * @param createtime the value for bus_rent.createtime
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}