package com.song.pojo;

public class SysMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.id
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.pid
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.title
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.href
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    private String href;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.spread
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    private Integer spread;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.target
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    private String target;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.icon
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.available
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    private Integer available;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.id
     *
     * @return the value of sys_menu.id
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.id
     *
     * @param id the value for sys_menu.id
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.pid
     *
     * @return the value of sys_menu.pid
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.pid
     *
     * @param pid the value for sys_menu.pid
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.title
     *
     * @return the value of sys_menu.title
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.title
     *
     * @param title the value for sys_menu.title
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.href
     *
     * @return the value of sys_menu.href
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public String getHref() {
        return href;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.href
     *
     * @param href the value for sys_menu.href
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public void setHref(String href) {
        this.href = href == null ? null : href.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.spread
     *
     * @return the value of sys_menu.spread
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public Integer getSpread() {
        return spread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.spread
     *
     * @param spread the value for sys_menu.spread
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public void setSpread(Integer spread) {
        this.spread = spread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.target
     *
     * @return the value of sys_menu.target
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public String getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.target
     *
     * @param target the value for sys_menu.target
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public void setTarget(String target) {
        this.target = target == null ? null : target.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.icon
     *
     * @return the value of sys_menu.icon
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.icon
     *
     * @param icon the value for sys_menu.icon
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.available
     *
     * @return the value of sys_menu.available
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public Integer getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.available
     *
     * @param available the value for sys_menu.available
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public void setAvailable(Integer available) {
        this.available = available;
    }
}