package com.song.pojo;

import java.util.Date;

public class SysNews {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_news.id
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_news.title
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_news.content
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_news.createtime
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_news.opername
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    private String opername;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_news.id
     *
     * @return the value of sys_news.id
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_news.id
     *
     * @param id the value for sys_news.id
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_news.title
     *
     * @return the value of sys_news.title
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_news.title
     *
     * @param title the value for sys_news.title
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_news.content
     *
     * @return the value of sys_news.content
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_news.content
     *
     * @param content the value for sys_news.content
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_news.createtime
     *
     * @return the value of sys_news.createtime
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_news.createtime
     *
     * @param createtime the value for sys_news.createtime
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_news.opername
     *
     * @return the value of sys_news.opername
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public String getOpername() {
        return opername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_news.opername
     *
     * @param opername the value for sys_news.opername
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public void setOpername(String opername) {
        this.opername = opername == null ? null : opername.trim();
    }
}