package com.song.pojo;

public class SysRoleMenuKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_menu.rid
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    private Integer rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_menu.mid
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    private Integer mid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_menu.rid
     *
     * @return the value of sys_role_menu.rid
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_menu.rid
     *
     * @param rid the value for sys_role_menu.rid
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_menu.mid
     *
     * @return the value of sys_role_menu.mid
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_menu.mid
     *
     * @param mid the value for sys_role_menu.mid
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }
}