package com.song.pojo;

public class SysRoleUserKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_user.uid
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_user.rid
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    private Integer rid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_user.uid
     *
     * @return the value of sys_role_user.uid
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_user.uid
     *
     * @param uid the value for sys_role_user.uid
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_user.rid
     *
     * @return the value of sys_role_user.rid
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_user.rid
     *
     * @param rid the value for sys_role_user.rid
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }
}