package com.song.mapper;

import com.song.pojo.BusCar;
import com.song.pojo.BusCarExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BusCarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_car
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int countByExample(BusCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_car
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int deleteByExample(BusCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_car
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int deleteByPrimaryKey(String carnumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_car
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int insert(BusCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_car
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int insertSelective(BusCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_car
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    List<BusCar> selectByExample(BusCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_car
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    BusCar selectByPrimaryKey(String carnumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_car
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int updateByExampleSelective(@Param("record") BusCar record, @Param("example") BusCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_car
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int updateByExample(@Param("record") BusCar record, @Param("example") BusCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_car
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int updateByPrimaryKeySelective(BusCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_car
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int updateByPrimaryKey(BusCar record);
}