package com.song.mapper;

import com.song.pojo.BusRent;
import com.song.pojo.BusRentExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BusRentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_rent
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int countByExample(BusRentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_rent
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int deleteByExample(BusRentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_rent
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int deleteByPrimaryKey(String rentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_rent
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int insert(BusRent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_rent
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int insertSelective(BusRent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_rent
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    List<BusRent> selectByExample(BusRentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_rent
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    BusRent selectByPrimaryKey(String rentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_rent
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int updateByExampleSelective(@Param("record") BusRent record, @Param("example") BusRentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_rent
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int updateByExample(@Param("record") BusRent record, @Param("example") BusRentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_rent
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int updateByPrimaryKeySelective(BusRent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_rent
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int updateByPrimaryKey(BusRent record);
}