package com.song.mapper;

import com.song.pojo.SysNews;
import com.song.pojo.SysNewsExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysNewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_news
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int countByExample(SysNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_news
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int deleteByExample(SysNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_news
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_news
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int insert(SysNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_news
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int insertSelective(SysNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_news
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    List<SysNews> selectByExample(SysNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_news
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    SysNews selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_news
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int updateByExampleSelective(@Param("record") SysNews record, @Param("example") SysNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_news
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int updateByExample(@Param("record") SysNews record, @Param("example") SysNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_news
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int updateByPrimaryKeySelective(SysNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_news
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int updateByPrimaryKey(SysNews record);
}