package com.song.mapper;

import com.song.pojo.BusCustomer;
import com.song.pojo.BusCustomerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BusCustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_customer
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int countByExample(BusCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_customer
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int deleteByExample(BusCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_customer
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int deleteByPrimaryKey(String identity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_customer
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int insert(BusCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_customer
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int insertSelective(BusCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_customer
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    List<BusCustomer> selectByExample(BusCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_customer
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    BusCustomer selectByPrimaryKey(String identity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_customer
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int updateByExampleSelective(@Param("record") BusCustomer record, @Param("example") BusCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_customer
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int updateByExample(@Param("record") BusCustomer record, @Param("example") BusCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_customer
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int updateByPrimaryKeySelective(BusCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_customer
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int updateByPrimaryKey(BusCustomer record);
}