package com.song.mapper;

import com.song.pojo.SysLogLogin;
import com.song.pojo.SysLogLoginExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysLogLoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log_login
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int countByExample(SysLogLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log_login
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int deleteByExample(SysLogLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log_login
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log_login
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int insert(SysLogLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log_login
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int insertSelective(SysLogLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log_login
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    List<SysLogLogin> selectByExample(SysLogLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log_login
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    SysLogLogin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log_login
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int updateByExampleSelective(@Param("record") SysLogLogin record, @Param("example") SysLogLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log_login
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int updateByExample(@Param("record") SysLogLogin record, @Param("example") SysLogLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log_login
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int updateByPrimaryKeySelective(SysLogLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log_login
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int updateByPrimaryKey(SysLogLogin record);
}