package com.song.mapper;

import com.song.pojo.SysRoleUserExample;
import com.song.pojo.SysRoleUserKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysRoleUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int countByExample(SysRoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int deleteByExample(SysRoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int deleteByPrimaryKey(SysRoleUserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int insert(SysRoleUserKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int insertSelective(SysRoleUserKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    List<SysRoleUserKey> selectByExample(SysRoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int updateByExampleSelective(@Param("record") SysRoleUserKey record, @Param("example") SysRoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user
     *
     * @mbggenerated Sun Dec 01 17:35:42 CST 2019
     */
    int updateByExample(@Param("record") SysRoleUserKey record, @Param("example") SysRoleUserExample example);
}